[package]
name        = "tic-tac-toe"
description = "test"
version     = "0.1.0"
flix        = "0.58.1"
authors     = ["Gagan Chandan <gagan@gaganchandan.com>"]

[mvn-dependencies]
"org.openjfx:javafx-swing" = "24"

